const RE_YOUTUBE_VIDEO_ID =
  /(?:youtube\.com\/(?:watch\?(?:.*?&)?v=|shorts\/|embed\/)|youtu\.be\/)([a-zA-Z0-9_-]{11})/i;

const INNERTUBE_API_URL =
  'https://www.youtube.com/youtubei/v1/player?prettyPrint=false';
const INNERTUBE_CLIENT_VERSION = '20.10.38';
const INNERTUBE_CONTEXT = {
  client: {
    clientName: 'ANDROID',
    clientVersion: INNERTUBE_CLIENT_VERSION,
  },
};
const INNERTUBE_USER_AGENT =
  `com.google.android.youtube/${INNERTUBE_CLIENT_VERSION} (Linux; U; Android 14)`;

export type YoutubeSubtitleErrorCode =
  | 'NO_VIDEO_ID'
  | 'NO_CAPTIONS'
  | 'NO_TRACK_MATCH'
  | 'FETCH_FAILED'
  | 'INVALID_TRACK_URL'
  | 'TRANSCRIPT_PARSE_FAILED';

export class YoutubeSubtitleError extends Error {
  constructor(
    public readonly code: YoutubeSubtitleErrorCode,
    message: string,
  ) {
    super(`[YouTubeSubtitles:${code}] ${message}`);
  }
}

export interface YoutubeCaptionTrack {
  baseUrl: string;
  languageCode: string;
  name: string;
  kind?: string;
  isAutoGenerated: boolean;
}

export interface YoutubeSubtitleSegment {
  text: string;
  startMs: number;
  durationMs: number;
  lang: string;
}

export interface YoutubeSubtitleExtractionResult {
  videoId: string;
  languageCode: string;
  isAutoGenerated: boolean;
  segments: YoutubeSubtitleSegment[];
  extractedAt: number;
}

export interface ExtractYoutubeSubtitlesOptions {
  videoUrlOrId?: string;
  preferredLang?: string;
  captionTracks?: YoutubeCaptionTrack[];
  doc?: Document;
  fetchFn?: typeof fetch;
}

interface CaptionTrackLike {
  baseUrl?: unknown;
  languageCode?: unknown;
  kind?: unknown;
  name?: {
    simpleText?: unknown;
    runs?: Array<{ text?: unknown }>;
  };
}

export function isYoutubeWatchUrl(url: string): boolean {
  try {
    const parsed = new URL(url);
    if (parsed.hostname === 'youtu.be') return true;
    if (!parsed.hostname.includes('youtube.com')) return false;
    return (
      parsed.pathname === '/watch' ||
      parsed.pathname.startsWith('/shorts/') ||
      parsed.pathname.startsWith('/embed/')
    );
  } catch {
    return false;
  }
}

export function extractYoutubeVideoId(urlOrId: string): string | null {
  const input = (urlOrId ?? '').trim();
  if (!input) return null;

  if (/^[a-zA-Z0-9_-]{11}$/.test(input)) return input;

  const match = input.match(RE_YOUTUBE_VIDEO_ID);
  return match ? match[1] : null;
}

export function decodeHtmlEntities(text: string): string {
  return text
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&#x([0-9a-fA-F]+);/g, (_, hex: string) =>
      String.fromCodePoint(parseInt(hex, 16)),
    )
    .replace(/&#(\d+);/g, (_, dec: string) =>
      String.fromCodePoint(parseInt(dec, 10)),
    );
}

export function parseTranscriptXml(
  xml: string,
  lang: string,
): YoutubeSubtitleSegment[] {
  if (!xml) {
    throw new YoutubeSubtitleError(
      'TRANSCRIPT_PARSE_FAILED',
      'Transcript payload was empty.',
    );
  }

  const srv3Results: YoutubeSubtitleSegment[] = [];
  const pRegex = /<p\s+t="(\d+)"(?:\s+d="(\d+)")?[^>]*>([\s\S]*?)<\/p>/g;
  let pMatch: RegExpExecArray | null;

  while ((pMatch = pRegex.exec(xml)) !== null) {
    const startMs = Number.parseInt(pMatch[1], 10);
    const durationMs = Number.parseInt(pMatch[2] ?? '0', 10);
    const inner = pMatch[3] ?? '';

    let text = '';
    const sRegex = /<s[^>]*>([\s\S]*?)<\/s>/g;
    let sMatch: RegExpExecArray | null;
    while ((sMatch = sRegex.exec(inner)) !== null) {
      text += sMatch[1] ?? '';
    }

    if (!text) {
      text = inner.replace(/<[^>]+>/g, '');
    }

    text = decodeHtmlEntities(text).replace(/\s+/g, ' ').trim();
    if (!text) continue;

    srv3Results.push({ text, startMs, durationMs, lang });
  }

  if (srv3Results.length > 0) {
    return srv3Results;
  }

  const classicResults: YoutubeSubtitleSegment[] = [];
  const classicRegex =
    /<text(?:\s+[^>]*?)?start="([^"]+)"(?:\s+[^>]*?)?(?:dur="([^"]*)")?[^>]*>([\s\S]*?)<\/text>/g;
  let cMatch: RegExpExecArray | null;

  while ((cMatch = classicRegex.exec(xml)) !== null) {
    const startMs = Math.round(Number.parseFloat(cMatch[1]) * 1000);
    const durationMs = Math.round(
      Number.parseFloat(cMatch[2] || '0') * 1000,
    );
    const text = decodeHtmlEntities(cMatch[3] ?? '')
      .replace(/<[^>]+>/g, '')
      .replace(/\s+/g, ' ')
      .trim();

    if (!text) continue;
    classicResults.push({ text, startMs, durationMs, lang });
  }

  if (classicResults.length > 0) {
    return classicResults;
  }

  throw new YoutubeSubtitleError(
    'TRANSCRIPT_PARSE_FAILED',
    'Transcript payload had no parseable subtitle segments.',
  );
}

export function extractCaptionTracksFromWatchHtml(
  html: string,
): YoutubeCaptionTrack[] {
  const playerResponse = parseInlineJson(html, 'ytInitialPlayerResponse');
  return extractCaptionTracksFromPlayerResponse(playerResponse);
}

export function extractCaptionTracksFromDocument(
  doc: Document,
): YoutubeCaptionTrack[] {
  const scripts = doc.querySelectorAll('script');
  for (const script of scripts) {
    const content = script.textContent ?? '';
    if (!content.includes('ytInitialPlayerResponse')) continue;

    const parsed = parseInlineJson(content, 'ytInitialPlayerResponse');
    const tracks = extractCaptionTracksFromPlayerResponse(parsed);
    if (tracks.length > 0) {
      return tracks;
    }
  }

  const htmlTracks = extractCaptionTracksFromWatchHtml(
    doc.documentElement?.innerHTML ?? '',
  );
  if (htmlTracks.length > 0) return htmlTracks;

  throw new YoutubeSubtitleError(
    'NO_CAPTIONS',
    'No caption tracks were found in the page source.',
  );
}

export function selectCaptionTrack(
  tracks: YoutubeCaptionTrack[],
  preferredLang?: string,
): YoutubeCaptionTrack {
  if (!tracks.length) {
    throw new YoutubeSubtitleError('NO_CAPTIONS', 'No caption tracks available.');
  }

  const normalizedPreferred = preferredLang?.toLowerCase();
  const preferredBase = normalizedPreferred?.split('-')[0];

  const manualTracks = tracks.filter((t) => !t.isAutoGenerated);
  const all = [...manualTracks, ...tracks.filter((t) => t.isAutoGenerated)];

  if (normalizedPreferred) {
    const exactManual = manualTracks.find(
      (t) => t.languageCode.toLowerCase() === normalizedPreferred,
    );
    if (exactManual) return exactManual;

    const exactAny = tracks.find(
      (t) => t.languageCode.toLowerCase() === normalizedPreferred,
    );
    if (exactAny) return exactAny;

    if (preferredBase) {
      const baseManual = manualTracks.find(
        (t) => t.languageCode.toLowerCase().split('-')[0] === preferredBase,
      );
      if (baseManual) return baseManual;

      const baseAny = tracks.find(
        (t) => t.languageCode.toLowerCase().split('-')[0] === preferredBase,
      );
      if (baseAny) return baseAny;
    }
  }

  const best = all[0];
  if (!best) {
    throw new YoutubeSubtitleError(
      'NO_TRACK_MATCH',
      'No suitable caption track was found.',
    );
  }
  return best;
}

export async function extractYoutubeSubtitles(
  options: ExtractYoutubeSubtitlesOptions = {},
): Promise<YoutubeSubtitleExtractionResult> {
  const fetchFn = options.fetchFn ?? fetch;
  const videoUrlOrId = options.videoUrlOrId ?? options.doc?.location?.href;
  const videoId = videoUrlOrId ? extractYoutubeVideoId(videoUrlOrId) : null;

  if (!videoId) {
    throw new YoutubeSubtitleError(
      'NO_VIDEO_ID',
      'Could not determine a YouTube video id from the current URL.',
    );
  }

  let tracks = options.captionTracks ?? [];

  if (tracks.length === 0) {
    tracks = await fetchCaptionTracksViaInnerTube(videoId, fetchFn);
  }

  if (tracks.length === 0 && options.doc) {
    tracks = extractCaptionTracksFromDocument(options.doc);
  }

  if (tracks.length === 0) {
    throw new YoutubeSubtitleError(
      'NO_CAPTIONS',
      `No subtitles found for video ${videoId}.`,
    );
  }

  const track = selectCaptionTrack(tracks, options.preferredLang);
  const transcriptUrl = buildTranscriptUrl(track.baseUrl);

  const transcriptResp = await fetchFn(transcriptUrl, {
    headers: {
      'Accept-Language': options.preferredLang ?? 'en',
      'User-Agent': INNERTUBE_USER_AGENT,
    },
  });

  if (!transcriptResp.ok) {
    throw new YoutubeSubtitleError(
      'FETCH_FAILED',
      `Transcript request failed (${transcriptResp.status}).`,
    );
  }

  const transcriptXml = await transcriptResp.text();
  const segments = parseTranscriptXml(transcriptXml, track.languageCode);

  return {
    videoId,
    languageCode: track.languageCode,
    isAutoGenerated: track.isAutoGenerated,
    segments,
    extractedAt: Date.now(),
  };
}

async function fetchCaptionTracksViaInnerTube(
  videoId: string,
  fetchFn: typeof fetch,
): Promise<YoutubeCaptionTrack[]> {
  const resp = await fetchFn(INNERTUBE_API_URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'User-Agent': INNERTUBE_USER_AGENT,
    },
    body: JSON.stringify({
      context: INNERTUBE_CONTEXT,
      videoId,
    }),
  });

  if (!resp.ok) return [];

  const payload = await resp.json();
  return extractCaptionTracksFromPlayerResponse(payload);
}

function extractCaptionTracksFromPlayerResponse(
  playerResponse: unknown,
): YoutubeCaptionTrack[] {
  const trackList =
    (playerResponse as {
      captions?: {
        playerCaptionsTracklistRenderer?: {
          captionTracks?: CaptionTrackLike[];
        };
      };
    })?.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];

  if (!Array.isArray(trackList)) return [];

  return trackList
    .map((track) => {
      const baseUrl = typeof track.baseUrl === 'string' ? track.baseUrl : '';
      const languageCode =
        typeof track.languageCode === 'string' ? track.languageCode : '';
      const name = parseTrackName(track);
      const kind = typeof track.kind === 'string' ? track.kind : undefined;
      const isAutoGenerated = kind === 'asr';

      if (!baseUrl || !languageCode) return null;

      return {
        baseUrl,
        languageCode,
        name: name || languageCode,
        kind,
        isAutoGenerated,
      } as YoutubeCaptionTrack;
    })
    .filter((track): track is YoutubeCaptionTrack => track !== null);
}

function parseTrackName(track: CaptionTrackLike): string {
  const simpleText =
    typeof track.name?.simpleText === 'string' ? track.name.simpleText : '';
  if (simpleText) return simpleText;

  const runs = Array.isArray(track.name?.runs) ? track.name?.runs : [];
  return runs
    .map((run) => (typeof run.text === 'string' ? run.text : ''))
    .join('')
    .trim();
}

function buildTranscriptUrl(baseUrl: string): string {
  let parsed: URL;
  try {
    parsed = new URL(baseUrl, 'https://www.youtube.com');
  } catch {
    throw new YoutubeSubtitleError(
      'INVALID_TRACK_URL',
      'Caption track URL could not be parsed.',
    );
  }

  const host = parsed.hostname.toLowerCase();
  const isTrustedHost =
    host === 'youtube.com' ||
    host.endsWith('.youtube.com') ||
    host === 'youtube-nocookie.com' ||
    host.endsWith('.youtube-nocookie.com');

  if (!isTrustedHost) {
    throw new YoutubeSubtitleError(
      'INVALID_TRACK_URL',
      `Untrusted caption host: ${parsed.hostname}`,
    );
  }

  parsed.searchParams.set('fmt', 'srv3');
  return parsed.toString();
}

function parseInlineJson(source: string, globalName: string): unknown | null {
  const patterns = [
    `var ${globalName} =`,
    `window["${globalName}"] =`,
    `${globalName} =`,
  ];

  for (const pattern of patterns) {
    const assignmentIdx = source.indexOf(pattern);
    if (assignmentIdx < 0) continue;

    const objectStart = source.indexOf('{', assignmentIdx + pattern.length);
    if (objectStart < 0) continue;

    const objectEnd = findObjectLiteralEnd(source, objectStart);
    if (objectEnd < 0) continue;

    const rawJson = source.slice(objectStart, objectEnd + 1);
    try {
      return JSON.parse(rawJson);
    } catch {
      continue;
    }
  }

  return null;
}

function findObjectLiteralEnd(source: string, startIndex: number): number {
  let depth = 0;
  let quote: '"' | "'" | null = null;
  let escaped = false;

  for (let i = startIndex; i < source.length; i++) {
    const ch = source[i];

    if (quote) {
      if (escaped) {
        escaped = false;
        continue;
      }
      if (ch === '\\') {
        escaped = true;
        continue;
      }
      if (ch === quote) {
        quote = null;
      }
      continue;
    }

    if (ch === '"' || ch === "'") {
      quote = ch;
      continue;
    }

    if (ch === '{') {
      depth++;
      continue;
    }

    if (ch === '}') {
      depth--;
      if (depth === 0) return i;
    }
  }

  return -1;
}