import {
  decodeHtmlEntities,
  extractCaptionTracksFromWatchHtml,
  extractYoutubeSubtitles,
  extractYoutubeVideoId,
  isYoutubeWatchUrl,
  parseTranscriptXml,
  selectCaptionTrack,
} from './youtube-subtitles';

describe('youtube-subtitles', () => {
  it('extracts video id from watch URL', () => {
    const id = extractYoutubeVideoId(
      'https://www.youtube.com/watch?v=WHYMGNbPv2U&t=117s',
    );
    expect(id).toBe('WHYMGNbPv2U');
  });

  it('detects YouTube watch URL variants', () => {
    expect(isYoutubeWatchUrl('https://www.youtube.com/watch?v=WHYMGNbPv2U')).toBe(
      true,
    );
    expect(isYoutubeWatchUrl('https://youtu.be/WHYMGNbPv2U')).toBe(true);
    expect(isYoutubeWatchUrl('https://example.com/watch?v=WHYMGNbPv2U')).toBe(
      false,
    );
  });

  it('decodes common HTML entities', () => {
    const text = decodeHtmlEntities('A &amp; B &quot;test&quot; &#39;ok&#39;');
    expect(text).toBe('A & B "test" \'ok\'');
  });

  it('parses srv3 transcript XML', () => {
    const xml = `
      <transcript>
        <p t="0" d="1200"><s>Hello</s><s> world</s></p>
        <p t="1500" d="1000">How &amp; why</p>
      </transcript>
    `;
    const segments = parseTranscriptXml(xml, 'en');

    expect(segments).toEqual([
      { text: 'Hello world', startMs: 0, durationMs: 1200, lang: 'en' },
      { text: 'How & why', startMs: 1500, durationMs: 1000, lang: 'en' },
    ]);
  });

  it('parses classic transcript XML', () => {
    const xml = `
      <transcript>
        <text start="1.5" dur="2.0">I&#39;m here</text>
        <text start="4.0" dur="1.25">&lt;tag&gt;safe&lt;/tag&gt;</text>
      </transcript>
    `;

    const segments = parseTranscriptXml(xml, 'en');

    expect(segments).toEqual([
      { text: "I'm here", startMs: 1500, durationMs: 2000, lang: 'en' },
      { text: 'safe', startMs: 4000, durationMs: 1250, lang: 'en' },
    ]);
  });

  it('prefers manual track over ASR for preferred language', () => {
    const selected = selectCaptionTrack(
      [
        {
          baseUrl: 'https://www.youtube.com/api/timedtext?lang=en&kind=asr',
          languageCode: 'en',
          name: 'English (auto-generated)',
          kind: 'asr',
          isAutoGenerated: true,
        },
        {
          baseUrl: 'https://www.youtube.com/api/timedtext?lang=en',
          languageCode: 'en',
          name: 'English',
          isAutoGenerated: false,
        },
      ],
      'en-US',
    );

    expect(selected.isAutoGenerated).toBe(false);
    expect(selected.baseUrl).toContain('lang=en');
    expect(selected.baseUrl).not.toContain('kind=asr');
  });

  it('extracts caption tracks from watch HTML script payload', () => {
    const html = `
      <html>
        <body>
          <script>
            var ytInitialPlayerResponse = {
              "captions": {
                "playerCaptionsTracklistRenderer": {
                  "captionTracks": [
                    {
                      "baseUrl": "https://www.youtube.com/api/timedtext?lang=en",
                      "languageCode": "en",
                      "name": { "simpleText": "English" }
                    }
                  ]
                }
              }
            };
          </script>
        </body>
      </html>
    `;

    const tracks = extractCaptionTracksFromWatchHtml(html);
    expect(tracks).toHaveLength(1);
    expect(tracks[0].languageCode).toBe('en');
    expect(tracks[0].isAutoGenerated).toBe(false);
  });

  it('extracts subtitles from provided tracks and transcript payload', async () => {
    const result = await extractYoutubeSubtitles({
      videoUrlOrId: 'WHYMGNbPv2U',
      preferredLang: 'en',
      captionTracks: [
        {
          baseUrl: 'https://www.youtube.com/api/timedtext?lang=en',
          languageCode: 'en',
          name: 'English',
          isAutoGenerated: false,
        },
      ],
      fetchFn: async () =>
        new Response(
          '<transcript><p t="1000" d="800">First line</p><p t="1800" d="600">Second</p></transcript>',
          { status: 200 },
        ),
    });

    expect(result.videoId).toBe('WHYMGNbPv2U');
    expect(result.languageCode).toBe('en');
    expect(result.segments).toHaveLength(2);
    expect(result.segments[0].text).toBe('First line');
  });
});

const runLiveTest = process.env.SKIP_YOUTUBE_LIVE_TEST !== '1';
const maybeLiveTest = runLiveTest ? test : test.skip;

function formatMs(ms: number): string {
  const totalSeconds = Math.floor(ms / 1000);
  const minutes = Math.floor(totalSeconds / 60);
  const seconds = totalSeconds % 60;
  return `${minutes}:${String(seconds).padStart(2, '0')}`;
}

maybeLiveTest(
  'live regression: extracts subtitles for WHYMGNbPv2U',
  { timeout: 30000 },
  async () => {
    const result = await extractYoutubeSubtitles({
      videoUrlOrId: 'https://www.youtube.com/watch?v=WHYMGNbPv2U&t=117s',
      preferredLang: 'en',
    });

    const previewCount = 6;
    const preview = result.segments
      .slice(0, previewCount)
      .map((seg, idx) => `${idx + 1}. [${formatMs(seg.startMs)}] ${seg.text}`)
      .join('\n');

    console.info(
      `\n[Live Subtitle Preview: WHYMGNbPv2U | lang=${result.languageCode} | segments=${result.segments.length}]\n${preview}\n`,
    );

    expect(result.videoId).toBe('WHYMGNbPv2U');
    expect(result.segments.length).toBeGreaterThan(0);
    expect(result.languageCode.length).toBeGreaterThan(0);
  },
);
