import { beforeEach, describe, expect, it, vi } from 'vitest';

vi.mock('../youtube-subtitles', async () => {
  const actual = await vi.importActual<typeof import('../youtube-subtitles')>('../youtube-subtitles');
  return {
    ...actual,
    extractYoutubeSubtitles: vi.fn(),
    extractCaptionTracksFromDocument: vi.fn(() => []),
    extractYoutubeVideoId: vi.fn(() => 'WHYMGNbPv2U'),
  };
});

import { captureYouTubeSubtitles } from './subtitle-capture';
import {
  extractYoutubeSubtitles,
} from '../youtube-subtitles';

const mockExtractYoutubeSubtitles = vi.mocked(extractYoutubeSubtitles);

describe('video/subtitle-capture', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    window.history.pushState({}, '', '/watch?v=WHYMGNbPv2U');
  });

  it('maps extractor segments to legacy subtitle cues', async () => {
    mockExtractYoutubeSubtitles.mockResolvedValue({
      videoId: 'WHYMGNbPv2U',
      languageCode: 'en',
      isAutoGenerated: false,
      extractedAt: Date.now(),
      segments: [
        { text: 'First', startMs: 1000, durationMs: 600, lang: 'en' },
        { text: 'Second', startMs: 2000, durationMs: 700, lang: 'en' },
      ],
    });

    const cues = await captureYouTubeSubtitles('en', 1);

    expect(cues).toHaveLength(2);
    expect(cues[0]).toMatchObject({
      index: 0,
      startMs: 1000,
      endMs: 1600,
      text: 'First',
    });
    expect(cues[1]).toMatchObject({
      index: 1,
      startMs: 2000,
      endMs: 2700,
      text: 'Second',
    });
  });

  it('falls back to timedtext JSON3 when extractor returns no cues', async () => {
    mockExtractYoutubeSubtitles.mockResolvedValue({
      videoId: 'WHYMGNbPv2U',
      languageCode: 'en',
      isAutoGenerated: false,
      extractedAt: Date.now(),
      segments: [],
    });

    const fetchMock = vi
      .spyOn(globalThis, 'fetch')
      .mockImplementation(async (input: RequestInfo | URL) => {
        const url = String(input);
        if (url.includes('type=list')) {
          return new Response('<transcript><track lang_code="en" /></transcript>', {
            status: 200,
          });
        }
        if (url.includes('fmt=json3')) {
          return new Response(
            JSON.stringify({
              events: [
                { tStartMs: 500, dDurationMs: 1000, segs: [{ utf8: 'Fallback cue' }] },
              ],
            }),
            { status: 200 },
          );
        }
        return new Response('', { status: 404 });
      });

    const cues = await captureYouTubeSubtitles('en', 1);

    expect(cues).toHaveLength(1);
    expect(cues[0].text).toBe('Fallback cue');
    expect(fetchMock).toHaveBeenCalled();

    fetchMock.mockRestore();
  });
});
